// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace APID3.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Required]
    [DisallowNull]
    public string Name { get; set; }

    public int? Age { get; set; }

    public string Adress { get; set; }

    public int? TrackId { get; set; }

    [ForeignKey("TrackId")]
    [InverseProperty("Students")]
    public virtual Track Track { get; set; }
}