// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APID3.Models;

[Table("Track")]
public partial class Track
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public string location { get; set; }

    [InverseProperty("Track")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}